import { Channel, VideoItem } from '../types';

export const STARTER_VIDEOS: VideoItem[] = [
  // --- КИСЕЛЬЧИК ---
  {
    id: 'yt_kiselchik_1',
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'МОНТАЖ В AE, PR? ЭТО ПРОСТО!',
    desc: 'Пошаговый разбор легкого и эффектного монтажа в After Effects и Premiere Pro для новичков и профи.',
    category: 'ТЕХНОЛОГИИ',
    url: 'https://youtu.be/MC_sxGxu0oY?si=9E2etdIQUGyG-9mq',
    youtubeId: 'MC_sxGxu0oY',
    youtubeUrl: 'https://youtu.be/MC_sxGxu0oY?si=9E2etdIQUGyG-9mq',
    thumbnailUrl: 'https://img.youtube.com/vi/MC_sxGxu0oY/hqdefault.jpg',
    duration: '08:35',
    views: 164200,
    likes: 15400,
    dislikes: 120,
    earnings: 3284,
    lastMonetizedViews: 164200,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kc1',
        author: 'MotionFan',
        text: 'Спасибо за гайд по AE! Наконец-то понял, как работают графики скорости.',
        type: 'fan',
        reply: 'Всегда пожалуйста! В следующем выпуске разберем шейповую анимацию.',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 540,
        timestamp: Date.now() - 30000,
      },
    ],
  },
  {
    id: 'yt_kiselchik_2',
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'КРУТОЙ ПАК МОНТАЖА!',
    desc: 'Бесплатный пак пресетов, переходов, звуковых эффектов (SFX) и оверлеев для ваших видео!',
    category: 'ТЕХНОЛОГИИ',
    url: 'https://youtu.be/qAkvR1NLJp4?si=uJ1p0KyjKyt41CK1',
    youtubeId: 'qAkvR1NLJp4',
    youtubeUrl: 'https://youtu.be/qAkvR1NLJp4?si=uJ1p0KyjKyt41CK1',
    thumbnailUrl: 'https://img.youtube.com/vi/qAkvR1NLJp4/hqdefault.jpg',
    duration: '05:14',
    views: 298500,
    likes: 31200,
    dislikes: 180,
    earnings: 5970,
    lastMonetizedViews: 298500,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kc2',
        author: 'VFX_Master',
        text: 'Пак топовый, забрал себе в коллекцию! Звуки сочные 🔥',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 830,
        timestamp: Date.now() - 20000,
      },
    ],
  },
  {
    id: 'yt_kiselchik_3',
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'Я ПОТЕРЯЛСЯ В ГОРОДЕ ЖИТЕЛЕЙ В МАЙНКРАФТ | Кисельчик Minecraft',
    desc: 'Захватывающее приключение в тайном городе жителей деревни номер 13! Сможем ли мы найти выход?',
    category: 'ИГРЫ',
    url: 'https://youtu.be/qoCPsnGkFTk?si=LjyudwZtkJLTVQOK',
    youtubeId: 'qoCPsnGkFTk',
    youtubeUrl: 'https://youtu.be/qoCPsnGkFTk?si=LjyudwZtkJLTVQOK',
    thumbnailUrl: 'https://img.youtube.com/vi/qoCPsnGkFTk/hqdefault.jpg',
    duration: '16:20',
    views: 485000,
    likes: 54100,
    dislikes: 350,
    earnings: 9700,
    lastMonetizedViews: 485000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kc3',
        author: 'MineCrafter_777',
        text: 'Ура, Майнкрафт! Деревня жителей топ, Кисельчик как всегда на высоте!',
        type: 'subscriber',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1200,
        timestamp: Date.now() - 10000,
      },
    ],
  },
  {
    id: 'yt_kiselchik_shorts1',
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: '🎉100.000.000 просмотров на клипе - ГОЛОВЫ НА ЗАВТРАК🌟 #майнкрафт',
    desc: 'Празднуем невероятный юбилей — 100 миллионов просмотров на главном хите Головы на завтрак! #shorts #майнкрафт #головыназавтрак',
    category: 'МУЗЫКА',
    url: 'https://youtube.com/shorts/NCtf0UNI6W8?si=CQpvFrcg_cC4P69I',
    youtubeId: 'NCtf0UNI6W8',
    youtubeUrl: 'https://youtube.com/shorts/NCtf0UNI6W8?si=CQpvFrcg_cC4P69I',
    thumbnailUrl: 'https://i.ytimg.com/vi/NCtf0UNI6W8/hqdefault.jpg',
    duration: '00:45',
    isShort: true,
    views: 1250000,
    likes: 142000,
    dislikes: 850,
    earnings: 25000,
    lastMonetizedViews: 1250000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kcs_1',
        author: 'Kisel_Fan',
        text: '100 ЛЯМОВ! Этот трек легенда навсегда! 🔥🔥',
        type: 'fan',
        reply: 'Огромное спасибо всем вам! Это наша общая победа!',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 4210,
        timestamp: Date.now() - 15000,
      },
    ],
  },
  {
    id: 'yt_kiselchik_shorts2',
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: '🎁 Распаковка МАЙНКРАФТ товаров 👾 #майнкрафт #minecraft',
    desc: 'Купил кучу секретных игрушек, фигурок и мерча по Майнкрафту! Какая редкая фигурка выпадет? #shorts #распаковка #товары #игрушки',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtube.com/shorts/YsCSKAqHSCk?si=9f3EGtwb-R6AVsGm',
    youtubeId: 'YsCSKAqHSCk',
    youtubeUrl: 'https://youtube.com/shorts/YsCSKAqHSCk?si=9f3EGtwb-R6AVsGm',
    thumbnailUrl: 'https://i.ytimg.com/vi/YsCSKAqHSCk/hqdefault.jpg',
    duration: '00:52',
    isShort: true,
    views: 980000,
    likes: 98500,
    dislikes: 620,
    earnings: 19600,
    lastMonetizedViews: 980000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kcs_2',
        author: 'Steve_Crafter',
        text: 'Фигурка крипера просто топ! Где такую купить?',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1850,
        timestamp: Date.now() - 10000,
      },
    ],
  },
  {
    id: 'yt_kiselchik_regular',
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: '$1 vs $1,000,000,000 Futuristic Tech!',
    desc: 'Сравнение самых невероятных гаджетов и технологий будущего от одного доллара до миллиарда долларов!',
    category: 'ТЕХНОЛОГИИ',
    url: 'https://youtu.be/pAnGwRiQ4-4?si=TqO2JjIuS5uvXOyL',
    youtubeId: 'pAnGwRiQ4-4',
    youtubeUrl: 'https://youtu.be/pAnGwRiQ4-4?si=TqO2JjIuS5uvXOyL',
    thumbnailUrl: 'https://i.ytimg.com/vi/pAnGwRiQ4-4/hqdefault.jpg',
    duration: '16:34',
    views: 1870000,
    likes: 165000,
    dislikes: 1100,
    earnings: 37400,
    lastMonetizedViews: 1870000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kcr_1',
        author: 'FutureExplorer',
        text: 'Летающий автомобиль за миллиард — это будущее, которое уже наступило!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2430,
        timestamp: Date.now() - 8000,
      },
    ],
  },

  // --- А4 (бывший Шортс Мемы) ---
  {
    id: 'yt_a4_1',
    channelId: 'chan_meme_hub',
    channelName: 'А4',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    title: 'ОТКРЫЛИ ФУД ТРАК НА КОЛЕСАХ!',
    desc: 'Мы открыли свой собственный настоящий фудтрак на колесах и готовим самую необычную уличную еду для гостей!',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtu.be/ZKmfieXJjXc?si=gLwBUF0q1KgRwUjl',
    youtubeId: 'ZKmfieXJjXc',
    youtubeUrl: 'https://youtu.be/ZKmfieXJjXc?si=gLwBUF0q1KgRwUjl',
    thumbnailUrl: 'https://img.youtube.com/vi/ZKmfieXJjXc/hqdefault.jpg',
    duration: '18:42',
    views: 3420000,
    likes: 285000,
    dislikes: 2100,
    earnings: 68400,
    lastMonetizedViews: 3420000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'a4_c1',
        author: 'Глент_Топ',
        text: 'Фудтрак получился пушка! Кто успел попробовать бургер ставьте лайк 🔥',
        type: 'fan',
        reply: 'Спасибо всем, кто пришел! В следующем выпуске сделаем еще масштабнее!',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 4230,
        isPinned: true,
        timestamp: Date.now() - 60000,
      },
    ],
  },
  {
    id: 'yt_a4_2',
    channelId: 'chan_meme_hub',
    channelName: 'А4',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    title: '100 ПОДВОДНЫХ КНОПОК!',
    desc: '100 таинственных кнопок на дне бассейна! Каждая кнопка запускает неожиданное действие, приз или жесткое наказание.',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtu.be/rzlfPJtrLGI?si=SSkFoXyX9DUbdtD9',
    youtubeId: 'rzlfPJtrLGI',
    youtubeUrl: 'https://youtu.be/rzlfPJtrLGI?si=SSkFoXyX9DUbdtD9',
    thumbnailUrl: 'https://img.youtube.com/vi/rzlfPJtrLGI/hqdefault.jpg',
    duration: '21:15',
    views: 4890000,
    likes: 410000,
    dislikes: 3400,
    earnings: 97800,
    lastMonetizedViews: 4890000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'a4_c2',
        author: 'Кобяков_Фан',
        text: 'Подводный челлендж это нечто! Кнопка со слизью просто топ 😂',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2980,
        timestamp: Date.now() - 30000,
      },
    ],
  },
  {
    id: 'yt_a4_3',
    channelId: 'chan_meme_hub',
    channelName: 'А4',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    title: 'ПОБЕГ ИЗ КАРТОННОЙ ТЮРЬМЫ!',
    desc: 'Мы построили гигантскую картонную тюрьму с охраной, лазерами и ловушками! Получится ли сбежать?',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtu.be/ltS2imUTJzo?si=T3ypD4k8jce4o2mP',
    youtubeId: 'ltS2imUTJzo',
    youtubeUrl: 'https://youtu.be/ltS2imUTJzo?si=T3ypD4k8jce4o2mP',
    thumbnailUrl: 'https://img.youtube.com/vi/ltS2imUTJzo/hqdefault.jpg',
    duration: '19:50',
    views: 5620000,
    likes: 520000,
    dislikes: 4100,
    earnings: 112400,
    lastMonetizedViews: 5620000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'a4_c3',
        author: 'A4_Legend',
        text: 'Это лучший побег из всех! Картонная охрана просто гениальна!',
        type: 'subscriber',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 5410,
        timestamp: Date.now() - 15000,
      },
    ],
  },

  // --- КИБЕР ДЕТЕКТИВ ---
  {
    id: 'yt_kd_steam',
    channelId: 'chan_cyber_investigator',
    channelName: 'Кибер Детектив',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: '😱Я Проверил Рандомные Стим Ключи на СКАМ !!!',
    desc: 'Купил сотни дешевых рандомных ключей Steam на разных сайтах и проверил, сколько там реального обмана и фейка!',
    category: 'РАЗБОР',
    url: 'https://youtu.be/yQz9FpN1wT0?si=gwj0ubBrbJIEQ9jf',
    youtubeId: 'yQz9FpN1wT0',
    youtubeUrl: 'https://youtu.be/yQz9FpN1wT0?si=gwj0ubBrbJIEQ9jf',
    thumbnailUrl: 'https://img.youtube.com/vi/yQz9FpN1wT0/hqdefault.jpg',
    duration: '14:22',
    views: 745000,
    likes: 64200,
    dislikes: 580,
    earnings: 14900,
    lastMonetizedViews: 745000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kd_c1',
        author: 'SteamHunter',
        text: 'Никогда больше не куплю рандомные ключи, спасибо за разоблачение!',
        type: 'fan',
        reply: 'Вот именно, берегите свои деньги и не ведитесь на халяву.',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1140,
        timestamp: Date.now() - 40000,
      },
    ],
  },
  {
    id: 'yt_kd_cs2',
    channelId: 'chan_cyber_investigator',
    channelName: 'Кибер Детектив',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: '😱Я Сделал свою Counter-Strike 2 , потому что мне не дали в неё поиграть...',
    desc: 'Пока все ждали доступ к бете CS2, я решил сделать собственную версию Counter-Strike 2 с нуля на игровом движке!',
    category: 'ИГРЫ',
    url: 'https://youtu.be/uq5X-xWaQvs?si=NsNk6j_ZnS_9p3RH',
    youtubeId: 'uq5X-xWaQvs',
    youtubeUrl: 'https://youtu.be/uq5X-xWaQvs?si=NsNk6j_ZnS_9p3RH',
    thumbnailUrl: 'https://img.youtube.com/vi/uq5X-xWaQvs/hqdefault.jpg',
    duration: '16:08',
    views: 890000,
    likes: 81000,
    dislikes: 720,
    earnings: 17800,
    lastMonetizedViews: 890000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kd_c2',
        author: 'GamerGuy_CS',
        text: 'Физика дыма получилась даже лучше, чем у Valve! Красава!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 920,
        timestamp: Date.now() - 20000,
      },
    ],
  },

  // --- РОБЕРТ ДО НИЛА (ранее Техно Вектор) ---
  {
    id: 'yt_kd_gta6',
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: '😱Я СДЕЛАЛ - GTA 6',
    desc: 'Воссоздал графику нового поколения, физику машин и открытый город GTA 6 на движке Unreal Engine!',
    category: 'ТЕХНОЛОГИИ',
    url: 'https://youtu.be/UXd3OJV5r_o?si=sGK-QTvbdEDyJaYL',
    youtubeId: 'UXd3OJV5r_o',
    youtubeUrl: 'https://youtu.be/UXd3OJV5r_o?si=sGK-QTvbdEDyJaYL',
    thumbnailUrl: 'https://img.youtube.com/vi/UXd3OJV5r_o/hqdefault.jpg',
    duration: '15:45',
    views: 920000,
    likes: 89500,
    dislikes: 640,
    earnings: 18400,
    lastMonetizedViews: 920000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'tv_c1',
        author: 'UnrealDev',
        text: 'Освещение с Lumen выглядит просто кинематографично!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1450,
        timestamp: Date.now() - 50000,
      },
    ],
  },
  {
    id: 'yt_kd_gta5_real',
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: '😱Я Превратил GTA 5 в Реальную Жизнь ! и вот что получилось...',
    desc: 'Установил фотореалистичные моды, трассировку лучей и 8K текстуры в GTA 5. Выглядит в точности как фильм!',
    category: 'ТЕХНОЛОГИИ',
    url: 'https://youtu.be/rKZ4_wHcJOg?si=xTXmjP2A7-n5whYY',
    youtubeId: 'rKZ4_wHcJOg',
    youtubeUrl: 'https://youtu.be/rKZ4_wHcJOg?si=xTXmjP2A7-n5whYY',
    thumbnailUrl: 'https://img.youtube.com/vi/rKZ4_wHcJOg/hqdefault.jpg',
    duration: '17:30',
    views: 1140000,
    likes: 104000,
    dislikes: 890,
    earnings: 22800,
    lastMonetizedViews: 1140000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'tv_c2',
        author: 'RayTracing_Fan',
        text: 'Моя видеокарта заплакала при одном виде этого ролика 😂 Качество бомба!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2100,
        timestamp: Date.now() - 35000,
      },
    ],
  },
  {
    id: 'yt_robert_cuphead',
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: '😱Учу Нейросеть Играть В Cuphead!',
    desc: 'Обучил искусственный интеллект с подкреплением проходить самых сложных боссов в игре Cuphead! Сможет ли ИИ одолеть Дьявола?',
    category: 'ИГРЫ',
    url: 'https://youtu.be/SAzDZhSSa_c?si=OZK1OmJZNW-QZkXB',
    youtubeId: 'SAzDZhSSa_c',
    youtubeUrl: 'https://youtu.be/SAzDZhSSa_c?si=OZK1OmJZNW-QZkXB',
    thumbnailUrl: 'https://i.ytimg.com/vi/SAzDZhSSa_c/hqdefault.jpg',
    duration: '18:15',
    views: 780000,
    likes: 79000,
    dislikes: 540,
    earnings: 15600,
    lastMonetizedViews: 780000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'rob_c1',
        author: 'AI_Researcher',
        text: 'Графики наград и функция потерь — это восторг! ИИ учится быстрее людей 🤖',
        type: 'fan',
        reply: 'В следующей серии обучим нейросеть спидранить Dark Souls!',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1320,
        timestamp: Date.now() - 25000,
      },
    ],
  },
  {
    id: 'yt_robert_montage',
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: '😏Спорим, Я Научу Тебя Монтировать За 15 Минут!',
    desc: 'Полный экспресс-гайд по видеомонтажу. Всё самое главное: динамические склейки, саунд-дизайн, анимации и цветокоррекция за 15 минут! #советыначинающимвмонтаже #пакмонтажа',
    category: 'ТЕХНОЛОГИИ',
    url: 'https://youtu.be/aMDL8Io9p14?si=tZOIv1NTjeLpYf1j',
    youtubeId: 'aMDL8Io9p14',
    youtubeUrl: 'https://youtu.be/aMDL8Io9p14?si=tZOIv1NTjeLpYf1j',
    thumbnailUrl: 'https://i.ytimg.com/vi/aMDL8Io9p14/hqdefault.jpg',
    duration: '15:42',
    views: 920000,
    likes: 98000,
    dislikes: 430,
    earnings: 18400,
    lastMonetizedViews: 920000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'rob_c2',
        author: 'VideoMaker_01',
        text: 'Спасибо за советы начинающим в монтаже! Смонтировал свой первый ролик по твоему гайду, получилось супер!',
        type: 'fan',
        reply: 'Рад помочь начинающим! Главное — тренироваться каждый день и делать чистый звук 👍',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2150,
        timestamp: Date.now() - 12000,
      },
      {
        id: 'rob_c3',
        author: 'Pro_Editor_Guy',
        text: 'А где скачать пак монтажа? Ссылка в описании роликов рабочая? 🔥',
        type: 'subscriber',
        reply: 'Да, ссылка на пак монтажа прямо в описании! Пользуйтесь на здоровье!',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1840,
        timestamp: Date.now() - 6000,
      },
    ],
  },

  // --- КОМПОТ ---
  {
    id: 'yt_kompot_1',
    channelId: 'chan_kompot',
    channelName: 'Компот',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'ЭТО САМАЯ НЕ СТРАШНАЯ СТРАШИЛКА В МАЙНКРАФТ | Компот Minecraft',
    desc: 'В деревне номер 13 начали происходить странные мистические вещи, но вместо страха вышло очень смешно!',
    category: 'ИГРЫ',
    url: 'https://youtu.be/1C3EsHFhT_c?si=l895DbyTVcbqY7at',
    youtubeId: '1C3EsHFhT_c',
    youtubeUrl: 'https://youtu.be/1C3EsHFhT_c?si=l895DbyTVcbqY7at',
    thumbnailUrl: 'https://img.youtube.com/vi/1C3EsHFhT_c/hqdefault.jpg',
    duration: '20:12',
    views: 2150000,
    likes: 184000,
    dislikes: 1200,
    earnings: 43000,
    lastMonetizedViews: 2150000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kp_c1',
        author: 'Житель_Кузнец',
        text: 'Компот лучший! Жители деревни передают привет! ❤️',
        type: 'fan',
        reply: 'Всем жителям огромный привет! Скоро новая серия!',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 3150,
        timestamp: Date.now() - 25000,
      },
    ],
  },
  {
    id: 'yt_kompot_2',
    channelId: 'chan_kompot',
    channelName: 'Компот',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'НИКОГДА НЕ ДОВЕРЯЙ ЭТОЙ СОБАКЕ В МАЙНКРАФТ | Компот Minecraft',
    desc: 'Приручил необычную собаку в деревне жителей, но она оказалась с огромным секретом...',
    category: 'ИГРЫ',
    url: 'https://youtu.be/OcqMhfXpFxA?si=Bw8BqsHOM-8lFUNo',
    youtubeId: 'OcqMhfXpFxA',
    youtubeUrl: 'https://youtu.be/OcqMhfXpFxA?si=Bw8BqsHOM-8lFUNo',
    thumbnailUrl: 'https://img.youtube.com/vi/OcqMhfXpFxA/hqdefault.jpg',
    duration: '18:50',
    views: 2680000,
    likes: 215000,
    dislikes: 1600,
    earnings: 53600,
    lastMonetizedViews: 2680000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kp_c2',
        author: 'DogLover_MC',
        text: 'Я думал собака добрая, а она такое вытворила! Неожиданная концовка 🐕',
        type: 'subscriber',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1980,
        timestamp: Date.now() - 15000,
      },
    ],
  },
  {
    id: 'yt_kompot_3',
    channelId: 'chan_kompot',
    channelName: 'Компот',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'НИКОГДА НЕ ДОВЕРЯЙ ЭТОМУ ИГРОКУ В МАЙНКРАФТ | Компот Minecraft',
    desc: 'В деревню пришел неизвестный игрок и притворился другом жителей. Что он задумал и как его разоблачить?',
    category: 'ИГРЫ',
    url: 'https://youtu.be/nNP4NZQp7pc?si=OEkgkD_BMOUXUU-v',
    youtubeId: 'nNP4NZQp7pc',
    youtubeUrl: 'https://youtu.be/nNP4NZQp7pc?si=OEkgkD_BMOUXUU-v',
    thumbnailUrl: 'https://img.youtube.com/vi/nNP4NZQp7pc/hqdefault.jpg',
    duration: '22:04',
    views: 3120000,
    likes: 279000,
    dislikes: 1900,
    earnings: 62400,
    lastMonetizedViews: 3120000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kp_c3',
        author: 'Alex_Pro_Play',
        text: 'Сюжет держит до самого конца! Компот лучший ютубер по Майнкрафту!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 3840,
        timestamp: Date.now() - 5000,
      },
    ],
  },
  {
    id: 'yt_kompot_4',
    channelId: 'chan_kompot',
    channelName: 'Компот',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'НИКОГДА НЕ ДОВЕРЯЙ ЭТОМУ ЖИТЕЛЮ В МАЙНКРАФТ | Компот Minecraft',
    desc: 'В деревне номер 13 появился загадочный житель, который торгует подозрительными предметами и скрывает подземную лабораторию...',
    category: 'ИГРЫ',
    url: 'https://youtu.be/vMeFy-LPXpk?si=pegy4AlARjV415Pi',
    youtubeId: 'vMeFy-LPXpk',
    youtubeUrl: 'https://youtu.be/vMeFy-LPXpk?si=pegy4AlARjV415Pi',
    thumbnailUrl: 'https://i.ytimg.com/vi/vMeFy-LPXpk/hqdefault.jpg',
    duration: '21:18',
    views: 2450000,
    likes: 210000,
    dislikes: 1400,
    earnings: 49000,
    lastMonetizedViews: 2450000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kp_c4',
        author: 'DiamondMiner',
        text: 'Этот житель сразу показался мне мутным! Компот, будь осторожен в шахте!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2140,
        timestamp: Date.now() - 4000,
      },
    ],
  },
  {
    id: 'yt_kompot_5',
    channelId: 'chan_kompot',
    channelName: 'Компот',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'Я ОТДАЛ ЭТОМУ ЖИТЕЛЮ ВСЁ ЧТО У МЕНЯ БЫЛО В МАЙНКРАФТ | Компот Minecraft',
    desc: 'Сумасшедший эксперимент в деревне номер 13: я отдал жителю все алмазы, броню и ресурсы кузницы!',
    category: 'ИГРЫ',
    url: 'https://youtu.be/d1Rc75x810o?si=izZ8R77RheLyAMZc',
    youtubeId: 'd1Rc75x810o',
    youtubeUrl: 'https://youtu.be/d1Rc75x810o?si=izZ8R77RheLyAMZc',
    thumbnailUrl: 'https://i.ytimg.com/vi/d1Rc75x810o/hqdefault.jpg',
    duration: '19:42',
    views: 2890000,
    likes: 245000,
    dislikes: 1650,
    earnings: 57800,
    lastMonetizedViews: 2890000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kp_c5',
        author: 'CreeperHunter',
        text: 'Я бы никогда не рискнул отдать весь свой инвентарь! Концовка просто шок 😲',
        type: 'subscriber',
        reply: 'Житель обещал вернуть с процентами, но...',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 3100,
        timestamp: Date.now() - 3000,
      },
    ],
  },
  {
    id: 'yt_kompot_6',
    channelId: 'chan_kompot',
    channelName: 'Компот',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'ТАК ВОТ КУДА ПРОПАЛ ЭТОТ ЖИТЕЛЬ В МАЙНКРАФТ | Компот Minecraft',
    desc: 'Мы нашли тайную тропу и секретный бункер! Оказывается, старейшина деревни скрывал портал в другое измерение.',
    category: 'ИГРЫ',
    url: 'https://youtu.be/LfGrLxbyXJU?si=b7IQ00OJYi59bz3u',
    youtubeId: 'LfGrLxbyXJU',
    youtubeUrl: 'https://youtu.be/LfGrLxbyXJU?si=b7IQ00OJYi59bz3u',
    thumbnailUrl: 'https://i.ytimg.com/vi/LfGrLxbyXJU/hqdefault.jpg',
    duration: '23:05',
    views: 3340000,
    likes: 298000,
    dislikes: 2100,
    earnings: 66800,
    lastMonetizedViews: 3340000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kp_c6',
        author: 'RedstoneMaster',
        text: 'Тайный бункер построен гениально, ловушки просто топ!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 1980,
        timestamp: Date.now() - 2000,
      },
    ],
  },
  {
    id: 'yt_kompot_7',
    channelId: 'chan_kompot',
    channelName: 'Компот',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'АДМИН РАЗБАНИЛ САМОГО ОПАСНОГО ЖИТЕЛЯ В МАЙНКРАФТ | Компот Minecraft',
    desc: 'Опаснейший забаненный житель вернулся! Кузница в опасности, вся деревня объединяется для защиты.',
    category: 'ИГРЫ',
    url: 'https://youtu.be/s5uuwMkOz94?si=1a-ONjh799g6Gzzo',
    youtubeId: 's5uuwMkOz94',
    youtubeUrl: 'https://youtu.be/s5uuwMkOz94?si=1a-ONjh799g6Gzzo',
    thumbnailUrl: 'https://i.ytimg.com/vi/s5uuwMkOz94/hqdefault.jpg',
    duration: '20:45',
    views: 3780000,
    likes: 320000,
    dislikes: 2300,
    earnings: 75600,
    lastMonetizedViews: 3780000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'kp_c7',
        author: 'IronGolemFan',
        text: 'Битва на крыше кузницы — это чистый кинематограф!',
        type: 'fan',
        reply: 'Железный голем спас ситуацию в самый последний момент!',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 4120,
        timestamp: Date.now() - 1000,
      },
    ],
  },

  // --- MrBeast (Самый популярный канал) ---
  {
    id: 'yt_mrbeast_squid',
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: '$456,000 Squid Game In Real Life!',
    desc: 'Воссоздали все испытания из сериала «Игра в Кальмара» в реальной жизни с 456 участниками и призовым фондом $456,000!',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtu.be/0e3GPea1Tyg?si=MihnSgZoDfEbKP-H',
    youtubeId: '0e3GPea1Tyg',
    youtubeUrl: 'https://youtu.be/0e3GPea1Tyg?si=MihnSgZoDfEbKP-H',
    thumbnailUrl: 'https://i.ytimg.com/vi/0e3GPea1Tyg/hqdefault.jpg',
    duration: '25:41',
    views: 640000000,
    likes: 16500000,
    dislikes: 74000,
    earnings: 12800000,
    lastMonetizedViews: 640000000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'mb_c1',
        author: 'GlobalFan_01',
        text: 'The production quality is higher than Netflix! Absolutely legendary video!',
        type: 'fan',
        reply: 'Thank you so much! We spent months building these sets!',
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 85200,
        timestamp: Date.now() - 60000,
      },
    ],
  },
  {
    id: 'yt_mrbeast_obstacle',
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'World’s Deadliest Obstacle Course!',
    desc: 'Самая опасная и экстремальная полоса препятствий в истории: гигантские маятники, лава и прыжки на высоте!',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtu.be/PWirijQkH4M?si=_5WCSZNJ9QfstK__',
    youtubeId: 'PWirijQkH4M',
    youtubeUrl: 'https://youtu.be/PWirijQkH4M?si=_5WCSZNJ9QfstK__',
    thumbnailUrl: 'https://i.ytimg.com/vi/PWirijQkH4M/hqdefault.jpg',
    duration: '19:22',
    views: 220000000,
    likes: 9800000,
    dislikes: 42000,
    earnings: 4400000,
    lastMonetizedViews: 220000000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'mb_c2',
        author: 'AdrenalineJunkie',
        text: 'That last jump was insane! How do they even design these courses?!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 34100,
        timestamp: Date.now() - 40000,
      },
    ],
  },
  {
    id: 'yt_mrbeast_ronaldo',
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'Beat Ronaldo, Win $1,000,000',
    desc: 'MrBeast и Криштиану Роналду в грандиозном футбольном челлендже! Победитель забирает чемодан с $1,000,000!',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtu.be/0BjlBnfHcHM?si=mkMX5QrDdhg4bour',
    youtubeId: '0BjlBnfHcHM',
    youtubeUrl: 'https://youtu.be/0BjlBnfHcHM?si=mkMX5QrDdhg4bour',
    thumbnailUrl: 'https://i.ytimg.com/vi/0BjlBnfHcHM/hqdefault.jpg',
    duration: '22:15',
    views: 185000000,
    likes: 8900000,
    dislikes: 35000,
    earnings: 3700000,
    lastMonetizedViews: 185000000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'mb_c3',
        author: 'CR7_Legend',
        text: 'SIUUUU! The crossover nobody expected but everybody needed!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 62400,
        timestamp: Date.now() - 20000,
      },
    ],
  },
  {
    id: 'yt_mrbeast_risk500k',
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    channelAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    title: 'How Much Would You Risk For $500,000?',
    desc: 'На что готовы пойти люди ради полмиллиона долларов? Огненные лабиринты, проверка нервов и невероятная развязка!',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtu.be/zo7i8VTpfNM',
    youtubeId: 'zo7i8VTpfNM',
    youtubeUrl: 'https://youtu.be/zo7i8VTpfNM',
    thumbnailUrl: 'https://i.ytimg.com/vi/zo7i8VTpfNM/hqdefault.jpg',
    duration: '24:50',
    views: 140000000,
    likes: 7200000,
    dislikes: 31000,
    earnings: 2800000,
    lastMonetizedViews: 140000000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'mb_c4',
        author: 'ThrillerFan',
        text: 'The psychological games in this episode were mindblowing!',
        type: 'fan',
        reply: null,
        dialogue: [],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 28900,
        timestamp: Date.now() - 10000,
      },
    ],
  },

  // 3 Shorts видео канала ЭЙР (YouTube Shorts)
  {
    id: 'yt_air_s1',
    channelId: 'chan_air',
    channelName: 'ЭЙР',
    title: 'ЧТО ОНИ СКРЫВАЛИ ВСЁ ЭТО ВРЕМЯ?! 🤯 #shorts',
    desc: 'Шокирующая правда, которую скрывали годами. Подписывайтесь на канал! #shorts #эйр',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtube.com/shorts/bTvXP8EpjKw?si=2uMBqXJveRI9oxZJ',
    youtubeId: 'bTvXP8EpjKw',
    youtubeUrl: 'https://youtube.com/shorts/bTvXP8EpjKw?si=2uMBqXJveRI9oxZJ',
    thumbnailUrl: 'https://i.ytimg.com/vi/bTvXP8EpjKw/hqdefault.jpg',
    duration: '0:42',
    isShort: true,
    views: 1840000,
    likes: 165000,
    dislikes: 850,
    earnings: 36800,
    lastMonetizedViews: 1840000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'air_s1_c1',
        author: 'Влад_2026',
        text: 'Офигеть, новый шортс и сразу такой кинематографичный разрыв! 🔥',
        type: 'fan',
        reply: 'Спасибо огромное за поддержку! Рад, что шортс залетел и вам понравилось! 🔥❤️',
        dialogue: [],
        repliesList: [
          {
            id: 'rep_auth_air_s1',
            author: 'ЭЙР',
            text: 'Спасибо огромное за поддержку! Рад, что шортс залетел и вам понравилось! 🔥❤️',
            likes: 1250,
            timestamp: Date.now() - 35000,
            isAuthor: true,
            verified: true,
            avatarColor: '#0284c7',
          },
        ],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 3400,
        timestamp: Date.now() - 40000,
      },
      {
        id: 'air_s1_c2',
        author: 'Матвей_Киноман',
        text: 'Сюжет за 40 секунд лучше, чем большинство фильмов в кино! Ждем еще!',
        type: 'fan',
        reply: 'Ценю каждого зрителя! Очень приятно видеть столько тепла в комментариях! ✨',
        dialogue: [],
        repliesList: [
          {
            id: 'rep_auth_air_s2',
            author: 'ЭЙР',
            text: 'Ценю каждого зрителя! Очень приятно видеть столько тепла в комментариях! ✨',
            likes: 890,
            timestamp: Date.now() - 20000,
            isAuthor: true,
            verified: true,
            avatarColor: '#0284c7',
          },
        ],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2100,
        timestamp: Date.now() - 25000,
      },
    ],
  },
  {
    id: 'yt_air_s2',
    channelId: 'chan_air',
    channelName: 'ЭЙР',
    title: 'НИКОГДА НЕ ПОВТОРЯЙТЕ ЭТО ДОМА ⚠️ #shorts',
    desc: 'Опасный эксперимент, который пошел не по плану. #shorts #эйр',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtube.com/shorts/hV7IB2C_2dk?si=BkLnsIQE50X8MhZk',
    youtubeId: 'hV7IB2C_2dk',
    youtubeUrl: 'https://youtube.com/shorts/hV7IB2C_2dk?si=BkLnsIQE50X8MhZk',
    thumbnailUrl: 'https://i.ytimg.com/vi/hV7IB2C_2dk/hqdefault.jpg',
    duration: '0:38',
    isShort: true,
    views: 2400000,
    likes: 210000,
    dislikes: 1100,
    earnings: 48000,
    lastMonetizedViews: 2400000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'air_s2_c1',
        author: 'Danik_Pro',
        text: 'Я пересмотрел три раза чтобы заметить эту деталь! Гениально!',
        type: 'fan',
        reply: 'Спасибо за просмотр и оценку! Рад, что ты обратил внимание на эту деталь 👍',
        dialogue: [],
        repliesList: [
          {
            id: 'rep_auth_air_s2_1',
            author: 'ЭЙР',
            text: 'Спасибо за просмотр и оценку! Рад, что ты обратил внимание на эту деталь 👍',
            likes: 1450,
            timestamp: Date.now() - 25000,
            isAuthor: true,
            verified: true,
            avatarColor: '#0284c7',
          },
        ],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 4200,
        timestamp: Date.now() - 30000,
      },
      {
        id: 'air_s2_c2',
        author: 'Alex_Master',
        text: 'Как ты это сделал?! Очень круто снято!',
        type: 'fan',
        reply: 'Спасибо за просмотр! Монтировал этот шортс несколько дней, рад вашей отдаче! 🚀',
        dialogue: [],
        repliesList: [
          {
            id: 'rep_auth_air_s2_2',
            author: 'ЭЙР',
            text: 'Спасибо за просмотр! Монтировал этот шортс несколько дней, рад вашей отдаче! 🚀',
            likes: 980,
            timestamp: Date.now() - 10000,
            isAuthor: true,
            verified: true,
            avatarColor: '#0284c7',
          },
        ],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2600,
        timestamp: Date.now() - 15000,
      },
    ],
  },
  {
    id: 'yt_air_s3',
    channelId: 'chan_air',
    channelName: 'ЭЙР',
    title: 'САМАЯ ЖЕСТКАЯ ТАЙНА РАСКРЫТА 😱 #shorts',
    desc: 'Третий ролик на канале. Всем приятного просмотра! #shorts #эйр',
    category: 'РАЗВЛЕЧЕНИЯ',
    url: 'https://youtube.com/shorts/p7TfNlwe9kI?si=OMS8tfoAMgS_kjUz',
    youtubeId: 'p7TfNlwe9kI',
    youtubeUrl: 'https://youtube.com/shorts/p7TfNlwe9kI?si=OMS8tfoAMgS_kjUz',
    thumbnailUrl: 'https://i.ytimg.com/vi/p7TfNlwe9kI/hqdefault.jpg',
    duration: '0:49',
    isShort: true,
    views: 3100000,
    likes: 290000,
    dislikes: 1400,
    earnings: 62000,
    lastMonetizedViews: 3100000,
    uploadedAt: Date.now(),
    comments: [
      {
        id: 'air_s3_c1',
        author: 'NightHunter',
        text: 'Аж мурашки по коже пошли... Умеешь атмосферу нагнетать!',
        type: 'fan',
        reply: 'Спасибо огромное! Читаю ваши комменты с улыбкой, вы лучшие! 💫',
        dialogue: [],
        repliesList: [
          {
            id: 'rep_auth_air_s3_1',
            author: 'ЭЙР',
            text: 'Спасибо огромное! Читаю ваши комменты с улыбкой, вы лучшие! 💫',
            likes: 1320,
            timestamp: Date.now() - 15000,
            isAuthor: true,
            verified: true,
            avatarColor: '#0284c7',
          },
        ],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 3800,
        timestamp: Date.now() - 20000,
      },
      {
        id: 'air_s3_c2',
        author: 'SuperFan',
        text: 'Каждый ролик как отдельный шедевр! Спасибо за контент!',
        type: 'fan',
        reply: 'Рад стараться для вас! Всем огромное спасибо за активность и лайки! ❤️',
        dialogue: [],
        repliesList: [
          {
            id: 'rep_auth_air_s3_2',
            author: 'ЭЙР',
            text: 'Рад стараться для вас! Всем огромное спасибо за активность и лайки! ❤️',
            likes: 1100,
            timestamp: Date.now() - 5000,
            isAuthor: true,
            verified: true,
            avatarColor: '#0284c7',
          },
        ],
        leftChannel: false,
        reformed: false,
        userReaction: null,
        joyReply: null,
        likes: 2900,
        timestamp: Date.now() - 10000,
      },
    ],
  },
];

export interface ScheduledVideoItem {
  channelId: string;
  channelName: string;
  releaseDelaySec: number;
  video: VideoItem;
}

/**
 * All premiere schedule intervals for non-user channels:
 * - Кисельчик: 60s, 180s, 300s, 420s, 540s, 720s
 * - Кибер Детектив: 90s, 330s
 * - Компот: 120s, 240s, 390s, 510s, 660s, 840s, 1020s
 * - Роберт До Нила: 150s, 360s, 570s, 750s
 * - А4: 300s, 480s, 780s
 * - MrBeast: 200s, 450s, 690s, 930s
 */
export const ALL_SCHEDULED_VIDEOS: ScheduledVideoItem[] = [
  // Кисельчик (обычные и Shorts)
  {
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kiselchik_1')!,
    releaseDelaySec: 60, // 1 мин
  },
  {
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kiselchik_2')!,
    releaseDelaySec: 180, // 3 мин
  },
  {
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kiselchik_3')!,
    releaseDelaySec: 300, // 5 мин
  },
  {
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kiselchik_shorts1')!,
    releaseDelaySec: 420, // 7 мин
  },
  {
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kiselchik_shorts2')!,
    releaseDelaySec: 540, // 9 мин
  },
  {
    channelId: 'chan_kiselchik',
    channelName: 'Кисельчик',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kiselchik_regular')!,
    releaseDelaySec: 720, // 12 мин
  },

  // Кибер Детектив
  {
    channelId: 'chan_cyber_investigator',
    channelName: 'Кибер Детектив',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kd_steam')!,
    releaseDelaySec: 90, // 1.5 мин
  },
  {
    channelId: 'chan_cyber_investigator',
    channelName: 'Кибер Детектив',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kd_cs2')!,
    releaseDelaySec: 330, // 5.5 мин
  },

  // Компот
  {
    channelId: 'chan_kompot',
    channelName: 'Компот',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kompot_1')!,
    releaseDelaySec: 120, // 2 мин
  },
  {
    channelId: 'chan_kompot',
    channelName: 'Компот',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kompot_2')!,
    releaseDelaySec: 240, // 4 мин
  },
  {
    channelId: 'chan_kompot',
    channelName: 'Компот',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kompot_3')!,
    releaseDelaySec: 390, // 6.5 мин
  },
  {
    channelId: 'chan_kompot',
    channelName: 'Компот',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kompot_4')!,
    releaseDelaySec: 510, // 8.5 мин
  },
  {
    channelId: 'chan_kompot',
    channelName: 'Компот',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kompot_5')!,
    releaseDelaySec: 660, // 11 мин
  },
  {
    channelId: 'chan_kompot',
    channelName: 'Компот',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kompot_6')!,
    releaseDelaySec: 840, // 14 мин
  },
  {
    channelId: 'chan_kompot',
    channelName: 'Компот',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kompot_7')!,
    releaseDelaySec: 1020, // 17 мин
  },

  // Роберт До Нила (бывший Техно Вектор)
  {
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kd_gta6')!,
    releaseDelaySec: 150, // 2.5 мин
  },
  {
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_kd_gta5_real')!,
    releaseDelaySec: 360, // 6 мин
  },
  {
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_robert_cuphead')!,
    releaseDelaySec: 570, // 9.5 мин
  },
  {
    channelId: 'chan_tech_future',
    channelName: 'Роберт До Нила',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_robert_montage')!,
    releaseDelaySec: 750, // 12.5 мин
  },

  // А4 (переименован из "Шортс Мемы"): 5 минут, потом через 3 мин, потом через 5 мин
  {
    channelId: 'chan_meme_hub',
    channelName: 'А4',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_a4_1')!,
    releaseDelaySec: 300, // 5 минут
  },
  {
    channelId: 'chan_meme_hub',
    channelName: 'А4',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_a4_2')!,
    releaseDelaySec: 480, // 5 + 3 = 8 минут
  },
  {
    channelId: 'chan_meme_hub',
    channelName: 'А4',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_a4_3')!,
    releaseDelaySec: 780, // 8 + 5 = 13 минут
  },

  // MrBeast (Самый популярный канал)
  {
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_mrbeast_squid')!,
    releaseDelaySec: 200, // ~3.3 мин
  },
  {
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_mrbeast_obstacle')!,
    releaseDelaySec: 450, // 7.5 мин
  },
  {
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_mrbeast_ronaldo')!,
    releaseDelaySec: 690, // 11.5 мин
  },
  {
    channelId: 'chan_mrbeast',
    channelName: 'MrBeast (Самый популярный канал)',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_mrbeast_risk500k')!,
    releaseDelaySec: 930, // 15.5 мин
  },

  // ЭЙР (3 Shorts)
  {
    channelId: 'chan_air',
    channelName: 'ЭЙР',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_air_s1')!,
    releaseDelaySec: 20,
  },
  {
    channelId: 'chan_air',
    channelName: 'ЭЙР',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_air_s2')!,
    releaseDelaySec: 220, // 20 минут в симуляции / 220 сек
  },
  {
    channelId: 'chan_air',
    channelName: 'ЭЙР',
    video: STARTER_VIDEOS.find((v) => v.id === 'yt_air_s3')!,
    releaseDelaySec: 420, // еще 20 минут / 420 сек
  },
];

export function getStarterCommentsForVideo(videoId: string) {
  const found = STARTER_VIDEOS.find((v) => v.id === videoId);
  if (found && found.comments) {
    return JSON.parse(JSON.stringify(found.comments));
  }
  return [];
}

export function getReleasedVideosForChannel(
  channelId: string,
  elapsedSec: number,
  premiereStartTime?: number
): VideoItem[] {
  const baseTime = premiereStartTime || (Date.now() - elapsedSec * 1000);
  return ALL_SCHEDULED_VIDEOS
    .filter((item) => item.channelId === channelId && elapsedSec >= item.releaseDelaySec)
    .map((item) => ({
      ...item.video,
      uploadedAt: baseTime + item.releaseDelaySec * 1000,
      comments: item.video.comments ? JSON.parse(JSON.stringify(item.video.comments)) : [],
    }));
}

export function getUpcomingVideoForChannel(
  channelId: string,
  elapsedSec: number
): { title: string; secondsLeft: number; channelName: string; video: VideoItem } | null {
  const upcoming = ALL_SCHEDULED_VIDEOS
    .filter((item) => item.channelId === channelId && elapsedSec < item.releaseDelaySec)
    .sort((a, b) => a.releaseDelaySec - b.releaseDelaySec)[0];

  if (!upcoming) return null;
  return {
    title: upcoming.video.title,
    secondsLeft: upcoming.releaseDelaySec - elapsedSec,
    channelName: upcoming.channelName,
    video: upcoming.video,
  };
}

export function getAllUpcomingPremieres(elapsedSec: number): Array<{
  channelId: string;
  channelName: string;
  secondsLeft: number;
  video: VideoItem;
}> {
  return ALL_SCHEDULED_VIDEOS
    .filter((item) => elapsedSec < item.releaseDelaySec)
    .map((item) => ({
      channelId: item.channelId,
      channelName: item.channelName,
      secondsLeft: item.releaseDelaySec - elapsedSec,
      video: item.video,
    }))
    .sort((a, b) => a.secondsLeft - b.secondsLeft);
}

export const DEFAULT_PLATFORM_CHANNELS: Channel[] = [
  {
    id: 'chan_kiselchik',
    name: 'Кисельчик',
    handle: '@kiselchik',
    desc: 'Канал Кисельчик! Обучалки по профессиональному видеомонтажу в After Effects и Premiere Pro, бесплатные паки ресурсов и топовые летсплеи по Майнкрафту.',
    subscribers: 432000,
    balance: 94000,
    avatarColor: '#f59e0b',
    bannerColor: '#b45309',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    monetization: { connected: true, connectedAt: Date.now() - 86400000 * 120 },
    verified: true,
    videos: [],
    createdAt: Date.now() - 86400000 * 200,
    isUserCreated: false,
    communityPosts: [
      {
        id: 'comm_kiselchik_1',
        channelId: 'chan_kiselchik',
        authorName: 'Кисельчик',
        authorHandle: '@kiselchik',
        authorColor: '#f59e0b',
        isChannelOwner: true,
        isVerified: true,
        text: 'Выложил новый бесплатный пак пресетов для After Effects и Premiere Pro! Ссылка в описании роликов. Как вам эффекты?',
        timestamp: Date.now() - 86400000 * 3,
        likes: 12400,
        comments: [
          {
            id: 'k_c1',
            author: 'Editor_2026',
            text: 'Пак просто пушка! Особенно понравился эффект глитча, спасибо огромное!',
            timestamp: Date.now() - 86400000 * 2,
            likes: 450,
          },
          {
            id: 'k_c2',
            author: 'MinecraftFan',
            text: 'А когда новое выживание с модами?',
            timestamp: Date.now() - 86400000 * 1,
            likes: 210,
          },
        ],
      },
      {
        id: 'comm_kiselchik_2',
        channelId: 'chan_kiselchik',
        authorName: 'Кисельчик',
        authorHandle: '@kiselchik',
        authorColor: '#f59e0b',
        isChannelOwner: true,
        isVerified: true,
        text: 'Голосуем, какой техно-ролик смонтировать следующим! 👇 #Чтоснять?',
        timestamp: Date.now() - 86400000 * 1,
        likes: 18900,
        poll: {
          question: 'Что протестировать в следующем видео?',
          options: [
            { id: 'kp_opt1', text: 'ПК за 15 000 руб с Авито', votes: 8400 },
            { id: 'kp_opt2', text: 'RTX 5090 в 8K разрешении', votes: 6200 },
            { id: 'kp_opt3', text: 'Самый дешевый смартфон с Ozon', votes: 4300 },
          ],
          totalVotes: 18900,
        },
        comments: [
          {
            id: 'k_c3',
            author: 'Gamer_Pro',
            text: 'Давай сними "ПК за 15 000 руб с Авито"! Всегда интересно посмотреть, что там продают)',
            timestamp: Date.now() - 86400000 * 1 + 5000,
            likes: 380,
          },
        ],
      },
      {
        id: 'comm_kiselchik_3',
        channelId: 'chan_kiselchik',
        authorName: 'Кисельчик',
        authorHandle: '@kiselchik',
        authorColor: '#f59e0b',
        isChannelOwner: true,
        isVerified: true,
        text: 'Привет всем подписчикам! Как ваши дела и учеба? Заглянул пообщаться в комментарии 😊 #Какделанеопрос!',
        timestamp: Date.now() - 86400000 * 0.4,
        likes: 9500,
        comments: [
          {
            id: 'k_c4',
            author: 'Danil_2026',
            text: 'Привет Кисельчик! Дела отлично, смотрю твои уроки по монтажу 🔥',
            timestamp: Date.now() - 86400000 * 0.3,
            likes: 120,
          },
        ],
      },
      {
        id: 'comm_kiselchik_4',
        channelId: 'chan_kiselchik',
        authorName: 'Кисельчик',
        authorHandle: '@kiselchik',
        authorColor: '#f59e0b',
        isChannelOwner: true,
        isVerified: true,
        text: 'Собрал полезнейшие фишки для новичков и выложил свежий набор эффектов! Делитесь результатами в комментах! #советыначинающимвмонтаже #пакмонтажа',
        timestamp: Date.now() - 86400000 * 0.1,
        likes: 14200,
        comments: [
          {
            id: 'k_c5',
            author: 'Novice_Creator',
            text: 'Спасибо огромное за советы начинающим в монтаже! С этим паком монтажа качество роликов сразу выросло в разы 🔥',
            timestamp: Date.now() - 86400000 * 0.08,
            likes: 820,
          },
          {
            id: 'k_c6',
            author: 'Max_Speed',
            text: 'Пак монтажа просто пушка! Все переходы и звуки скачались без проблем, респект!',
            timestamp: Date.now() - 86400000 * 0.05,
            likes: 640,
          },
        ],
      },
    ],
  },
  {
    id: 'chan_meme_hub',
    name: 'А4',
    handle: '@a4omg',
    desc: 'Официальный канал Влада А4! Новые масштабные челленджи, крутые видео, безумные постройки и смешные эксперименты каждый день!',
    subscribers: 48500000,
    balance: 1850000,
    avatarColor: '#f59e0b',
    bannerColor: '#b45309',
    bannerUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80',
    monetization: { connected: true, connectedAt: Date.now() - 86400000 * 500 },
    verified: true,
    videos: [],
    createdAt: Date.now() - 86400000 * 500,
    isUserCreated: false,
    communityPosts: [
      {
        id: 'comm_a4_1',
        channelId: 'chan_meme_hub',
        authorName: 'А4',
        authorHandle: '@a4omg',
        authorColor: '#f59e0b',
        isChannelOwner: true,
        isVerified: true,
        text: 'Привет подписчики! Снимаем новый масштабный ролик на 24 часа! Голосуйте, какой челлендж хотите увидеть следующим:',
        timestamp: Date.now() - 86400000 * 2,
        likes: 342000,
        poll: {
          question: 'Какой челлендж снять?',
          options: [
            { id: 'opt_1', text: '24 часа в закрытом батутном центре', votes: 142000 },
            { id: 'opt_2', text: 'Побег от охранника в огромном молле', votes: 118000 },
            { id: 'opt_3', text: 'Пол это лава в реальной жизни', votes: 82000 },
          ],
          totalVotes: 342000,
        },
        comments: [
          {
            id: 'a4_c1',
            author: 'Глеб_A4',
            text: 'Голосую за батутный центр! Это будет самый угарный ролик 😂',
            timestamp: Date.now() - 86400000 * 2 + 2000,
            likes: 1250,
          },
          {
            id: 'a4_c2',
            author: 'Алина_Super',
            text: 'Влад, ты лучший! Ждем новый мерч и ролик!',
            timestamp: Date.now() - 86400000 * 2 + 5000,
            likes: 890,
          },
        ],
      },
      {
        id: 'comm_a4_2',
        channelId: 'chan_meme_hub',
        authorName: 'А4',
        authorHandle: '@a4omg',
        authorColor: '#f59e0b',
        isChannelOwner: true,
        isVerified: true,
        text: 'Банда, как ваше настроение на этой неделе? Голосуйте в опросе! 👇 #Какдела?',
        timestamp: Date.now() - 86400000 * 1,
        likes: 295000,
        poll: {
          question: 'Как настроение у банды А4?',
          options: [
            { id: 'a4_h1', text: 'Бодрое и веселое! 🔥', votes: 165000 },
            { id: 'a4_h2', text: 'Отличное, жду ролик!', votes: 94000 },
            { id: 'a4_h3', text: 'Нормально 🙂', votes: 36000 },
          ],
          totalVotes: 295000,
        },
        comments: [
          {
            id: 'a4_c3',
            author: 'Тимофей_Pro',
            text: 'Проголосовал за Бодрое! Вы лучшие!',
            timestamp: Date.now() - 86400000 * 1 + 1000,
            likes: 1450,
          },
        ],
      },
      {
        id: 'comm_a4_3',
        channelId: 'chan_meme_hub',
        authorName: 'А4',
        authorHandle: '@a4omg',
        authorColor: '#f59e0b',
        isChannelOwner: true,
        isVerified: true,
        text: 'Привет всем! Новый мерч почти на складе, а мы готовим для вас сюрприз! Как проходит ваш день? ⚡️ #Какделанеопрос!',
        imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80',
        timestamp: Date.now() - 86400000 * 0.3,
        likes: 210000,
        comments: [
          {
            id: 'a4_c4',
            author: 'Макс_A4',
            text: 'Привет Влад! День супер, ждем мерч и новые серии!',
            timestamp: Date.now() - 86400000 * 0.2,
            likes: 920,
          },
        ],
      },
    ],
  },
  {
    id: 'chan_kompot',
    name: 'Компот',
    handle: '@kompot',
    desc: 'Привет! Я Компот (Roman Kompot), играю в Майнкрафт (Minecraft)! Уютные деревенские летсплеи, жители деревни номер 13 и тайны кубического мира.',
    subscribers: 14200000,
    balance: 980000,
    avatarColor: '#10b981',
    bannerColor: '#047857',
    bannerUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop&q=80',
    monetization: { connected: true, connectedAt: Date.now() - 86400000 * 400 },
    verified: true,
    videos: [],
    createdAt: Date.now() - 86400000 * 400,
    isUserCreated: false,
    communityPosts: [
      {
        id: 'comm_kompot_1',
        channelId: 'chan_kompot',
        authorName: 'Компот',
        authorHandle: '@kompot',
        authorColor: '#10b981',
        isChannelOwner: true,
        isVerified: true,
        text: 'Всем привет, жители деревни номер 13! Сегодня нашел заброшенную шахту прямо под кузницей. Спускаться туда в следующей серии?',
        timestamp: Date.now() - 86400000 * 2,
        likes: 98000,
        comments: [
          {
            id: 'kp_c1',
            author: 'Steve_2026',
            text: 'Дааа, спускайся! Возьми с собой побольше факелов и золотые яблоки!',
            timestamp: Date.now() - 86400000 * 2 + 1000,
            likes: 670,
          },
        ],
      },
      {
        id: 'comm_kompot_2',
        channelId: 'chan_kompot',
        authorName: 'Компот',
        authorHandle: '@kompot',
        authorColor: '#10b981',
        isChannelOwner: true,
        isVerified: true,
        text: 'Ребята, какую постройку сделать в деревне? Голосуйте за лучший вариант! 👇 #Чтоснять?',
        timestamp: Date.now() - 86400000 * 0.8,
        likes: 114000,
        poll: {
          question: 'Новая постройка в деревне номер 13:',
          options: [
            { id: 'km_opt1', text: 'Подземный бункер с ловушками', votes: 64000 },
            { id: 'km_opt2', text: 'Замок из бедрока', votes: 41000 },
            { id: 'km_opt3', text: 'Авто-ферма изумрудов', votes: 29000 },
          ],
          totalVotes: 134000,
        },
        comments: [
          {
            id: 'kp_c2',
            author: 'Mine_Bro',
            text: 'Давай сними "Подземный бункер с ловушками"! Будет самый эпичный выпуск! 🔥',
            timestamp: Date.now() - 86400000 * 0.7,
            likes: 1240,
          },
        ],
      },
      {
        id: 'comm_kompot_3',
        channelId: 'chan_kompot',
        authorName: 'Компот',
        authorHandle: '@kompot',
        authorColor: '#10b981',
        isChannelOwner: true,
        isVerified: true,
        text: 'Как у вас настроение сегодня, ребята? Не болейте и берегите себя! 👇 #Какдела?',
        timestamp: Date.now() - 86400000 * 0.2,
        likes: 76000,
        poll: {
          question: 'Как настроение у подписчиков Компота?',
          options: [
            { id: 'km_h1', text: 'Отлично! 🌾', votes: 42000 },
            { id: 'km_h2', text: 'Хорошо, играю в Майн', votes: 28000 },
            { id: 'km_h3', text: 'Устал после школы', votes: 12000 },
          ],
          totalVotes: 82000,
        },
        comments: [
          {
            id: 'kp_c3',
            author: 'Ilya_Pro',
            text: 'Проголосовал за Отлично! Спасибо за уютные видосы Компот ❤️',
            timestamp: Date.now() - 86400000 * 0.1,
            likes: 830,
          },
        ],
      },
    ],
  },
  {
    id: 'chan_cyber_investigator',
    name: 'Кибер Детектив',
    handle: '@cyber_detective',
    desc: 'Глубокие расследования темной стороны интернета, разоблачение мошенников, схемы накруток и проверка серых сеток.',
    subscribers: 284000,
    balance: 85400,
    avatarColor: '#dc2626',
    bannerColor: '#1a1a1a',
    bannerUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&auto=format&fit=crop&q=80',
    monetization: { connected: true, connectedAt: Date.now() - 86400000 * 300 },
    verified: true,
    videos: [],
    createdAt: Date.now() - 86400000 * 365,
    isUserCreated: false,
    communityPosts: [
      {
        id: 'comm_cyber_1',
        channelId: 'chan_cyber_investigator',
        authorName: 'Кибер Детектив',
        authorHandle: '@cyber_detective',
        authorColor: '#dc2626',
        isChannelOwner: true,
        isVerified: true,
        text: 'Готовлю новое расследование про черные схемы накрутки просмотров и ботнеты на видеохостингах. Материал собирался 2 месяца.',
        timestamp: Date.now() - 86400000 * 4,
        likes: 18400,
        comments: [
          {
            id: 'cd_c1',
            author: 'HackerMan',
            text: 'Очень ждем! Твои расследования всегда вскрывают всю правду!',
            timestamp: Date.now() - 86400000 * 3,
            likes: 310,
          },
        ],
      },
      {
        id: 'comm_cyber_2',
        channelId: 'chan_cyber_investigator',
        authorName: 'Кибер Детектив',
        authorHandle: '@cyber_detective',
        authorColor: '#dc2626',
        isChannelOwner: true,
        isVerified: true,
        text: 'Какое расследование выпустить следующим на канале? Голосуйте в опросе: 👇 #Чтоснять?',
        timestamp: Date.now() - 86400000 * 1.5,
        likes: 24500,
        poll: {
          question: 'Тема следующего расследования:',
          options: [
            { id: 'cd_opt1', text: 'Схемы со скам-играми', votes: 12400 },
            { id: 'cd_opt2', text: 'Тайны заброшенных серверов', votes: 8900 },
            { id: 'cd_opt3', text: 'Фейковые разоблачители', votes: 6100 },
          ],
          totalVotes: 27400,
        },
        comments: [
          {
            id: 'cd_c2',
            author: 'Agent_007',
            text: 'Давай сними "Схемы со скам-играми"! Давно пора вывести их на чистую воду!',
            timestamp: Date.now() - 86400000 * 1.4,
            likes: 420,
          },
        ],
      },
      {
        id: 'comm_cyber_3',
        channelId: 'chan_cyber_investigator',
        authorName: 'Кибер Детектив',
        authorHandle: '@cyber_detective',
        authorColor: '#dc2626',
        isChannelOwner: true,
        isVerified: true,
        text: 'Привет всем агентам и сыщикам! Как ваши дела сегодня? Все ли спокойно в сети? 😊 #Какделанеопрос!',
        timestamp: Date.now() - 86400000 * 0.5,
        likes: 14200,
        comments: [
          {
            id: 'cd_c3',
            author: 'InfoSecurity',
            text: 'Привет Детектив! Всё спокойно, пьем кофе и ждем премьеру)',
            timestamp: Date.now() - 86400000 * 0.4,
            likes: 180,
          },
        ],
      },
    ],
  },
  {
    id: 'chan_tech_future',
    name: 'Роберт До Нила',
    handle: '@robert_do_nila',
    desc: 'Официальный канал Роберт До Нила! Обучение монтажу за 15 минут, Cuphead с нейросетями, крутые эксперименты с видео и геймингом.',
    subscribers: 245000,
    balance: 64000,
    avatarColor: '#3b82f6',
    bannerColor: '#1e40af',
    bannerUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80',
    monetization: { connected: true, connectedAt: Date.now() - 86400000 * 180 },
    verified: true,
    videos: [],
    createdAt: Date.now() - 86400000 * 200,
    isUserCreated: false,
    communityPosts: [
      {
        id: 'comm_rdn_1',
        channelId: 'chan_tech_future',
        authorName: 'Роберт До Нила',
        authorHandle: '@robert_do_nila',
        authorColor: '#3b82f6',
        isChannelOwner: true,
        isVerified: true,
        text: 'Сижу на таймлайне уже 8 часов подряд, рендер 4K греет комнату лучше батареи 🎬💻 Всем хорошего вечера! #Какделанеопрос!',
        imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&auto=format&fit=crop&q=80',
        timestamp: Date.now() - 86400000 * 2,
        likes: 19500,
        comments: [
          {
            id: 'rdn_c1',
            author: 'MotionFan',
            text: 'Роберт, дай отдохнуть видеокарте ахаха! Ждем видос 🔥',
            timestamp: Date.now() - 86400000 * 1.9,
            likes: 290,
          },
        ],
      },
      {
        id: 'comm_rdn_2',
        channelId: 'chan_tech_future',
        authorName: 'Роберт До Нила',
        authorHandle: '@robert_do_nila',
        authorColor: '#3b82f6',
        isChannelOwner: true,
        isVerified: true,
        text: 'Какой кино-разбор сделать следующим? Выбирайте в опросе! 👇 #Чтоснять?',
        timestamp: Date.now() - 86400000 * 0.9,
        likes: 22100,
        poll: {
          question: 'Тема следующего кино-разбора:',
          options: [
            { id: 'rdn_opt1', text: 'Секреты скрытого монтажа', votes: 11000 },
            { id: 'rdn_opt2', text: 'Разбор спецэффектов Нолана', votes: 8500 },
            { id: 'rdn_opt3', text: 'Почему графика 2000-х была лучше', votes: 5200 },
          ],
          totalVotes: 24700,
        },
        comments: [
          {
            id: 'rdn_c2',
            author: 'Cinephile_99',
            text: 'Давай сними "Секреты скрытого монтажа"! Обожаю твои технические разборы!',
            timestamp: Date.now() - 86400000 * 0.8,
            likes: 310,
          },
        ],
      },
    ],
  },
  {
    id: 'chan_mrbeast',
    name: 'MrBeast (Самый популярный канал)',
    handle: '@MrBeast',
    desc: 'Официальный канал MrBeast — самый популярный канал на платформе! 360M+ подписчиков. Раздаем миллионы долларов, масштабные челленджи и выживание!',
    subscribers: 365000000,
    balance: 85000000,
    avatarColor: '#06b6d4',
    bannerColor: '#0891b2',
    bannerUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop&q=80',
    monetization: { connected: true, connectedAt: Date.now() - 86400000 * 1000 },
    verified: true,
    videos: [],
    createdAt: Date.now() - 86400000 * 1000,
    isUserCreated: false,
    communityPosts: [
      {
        id: 'comm_mrbeast_1',
        channelId: 'chan_mrbeast',
        authorName: 'MrBeast (Самый популярный канал)',
        authorHandle: '@MrBeast',
        authorColor: '#06b6d4',
        isChannelOwner: true,
        isVerified: true,
        text: 'I just built a real life Squid Game arena for our next video! What should the grand prize be?',
        timestamp: Date.now() - 86400000 * 2,
        likes: 1200000,
        poll: {
          question: 'Grand Prize Choice',
          options: [
            { id: 'mb_1', text: '$1,000,000 Cash', votes: 850000 },
            { id: 'mb_2', text: 'Private Tropical Island', votes: 230000 },
            { id: 'mb_3', text: 'Brand New Lamborghini', votes: 120000 },
          ],
          totalVotes: 1200000,
        },
        comments: [
          {
            id: 'mb_comm_1',
            author: 'JimmyFan',
            text: '$1,000,000 in cash would be insane! Can’t wait for this video!',
            timestamp: Date.now() - 86400000 * 2 + 10000,
            likes: 45000,
          },
        ],
      },
    ],
  },
  {
    id: 'chan_air',
    name: 'ЭЙР',
    handle: '@air',
    desc: 'Официальный канал ЭЙР. Авторские шортсы, кинематографичный контент и тайны!',
    subscribers: 104242,
    balance: 45000,
    avatarColor: '#0284c7',
    avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&auto=format&fit=crop&q=80',
    bannerColor: '#0369a1',
    bannerUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80',
    monetization: { connected: true, connectedAt: Date.now() - 86400000 * 365 },
    verified: true,
    videos: [],
    createdAt: Date.now() - 86400000 * 365,
    isUserCreated: false,
    communityPosts: [],
  },
];

